jobs:
  # Windows
  - template: azure-test-template-win.yml
    parameters:
      name: Windows_3_7
      vmImage: 'windows-2022'
      build_docs: 1
      python: '3.7'
      python_name: '3_7'
      allowFailure: true
  - template: azure-test-template-win.yml
    parameters:
      name: Windows_3_8
      vmImage: 'windows-2022'
      build_docs: 1
      python: '3.8'
      python_name: '3_8'
      allowFailure: true
  - template: azure-test-template-win.yml
    parameters:
      name: Windows_3_9
      vmImage: 'windows-2022'
      build_docs: 1
      python: '3.9'
      python_name: '3_9'
      allowFailure: true
